### ISSUE TITLE
Input History: show microseconds

### ISSUE THREAD

**Issue by mat1jaczyyy** [mat1jaczyyy/Keyboard-Inspector#30]
Should show microsecond range as well once you've zoomed in far enough.

**Comment by Missmerel** [comment]
ok

**Comment by mat1jaczyyy** [comment]
Resolved with [d3b9a8c](https://github.com/mat1jaczyyy/Keyboard-Inspector/commit/d3b9a8ccf47d8675f762429b1fffa2d505651a18)
