### ISSUE TITLE
no longer analyze interface for polling rate of keyboard in verson 1.0

### ISSUE THREAD

**Issue by mharbb** [mat1jaczyyy/Keyboard-Inspector#37]
Maybe I'm just stupid but I can't figure out how to analyze the polling rate of my keyboard.

**Comment by mat1jaczyyy** [comment]
old version makes really bad guesstimates, and often the polling process is more complex and cant be represented by a single number (scan+poll rates). new analysis is explained in readme

you can also always join our discord and ask for help (link in readme as well), this place is for discussion for development of the software
