### ISSUE TITLE
Avira Antivirus deny open the .exe

### ISSUE THREAD

**Issue by Anormalwolf** [mat1jaczyyy/Keyboard-Inspector#5]
![Captura](https://user-images.githubusercontent.com/77684945/134914484-4eaac89c-0e2f-4438-affc-7291a49c7efe.PNG)

**Comment by mat1jaczyyy** [comment]
Yeah, for some reason, since I added guitar support, all builds have been falsely flagged by any antivirus. This even happens to my own machine too. You should list it as a false positive, if you're skeptical there's always the option of compiling it yourself.

**Comment by mat1jaczyyy** [comment]
Hopefully no longer an issue on recent builds.
