### ISSUE TITLE
Windows antivirus prevents opening the program

### ISSUE THREAD

**Issue by goldengun111** [mat1jaczyyy/Keyboard-Inspector#8]
Installed version 0.3.0 and windows defender flagged the .exe as a potential trojan or unwanted software and would not allow me to open the program, even chrome doesn't allow you to install it as it flagged it as a dangerous program. 
downloaded it from the latest release on github not some shady site.  windows goes as far as to delete the program even though I allowed it to remain on my pc, I saw the comment about guitar support. Is there a chance to crate a separate version that doesn't have that as I personally don't care about guitar support so that windows stops falsely flagging the program.
https://imgur.com/a/Ld6X7Pe

**Comment by mat1jaczyyy** [comment]
I didn't close this back then, but 0.4.0 seems to not have this issue anymore, and there will be new versions coming up soon
