### ISSUE TITLE
Laptop Keyboard cant be analyze

### ISSUE THREAD

**Issue by LoneEvos** [mat1jaczyyy/Keyboard-Inspector#9]
The keyboard inspector cant analyze the polling rate of my laptop's keyboard

**Comment by mat1jaczyyy** [comment]
And how can I read your mind and your laptop's state? Attach a recording.

**Comment by LoneEvos** [comment]
![Screenshot_20230305_095850](https://user-images.githubusercontent.com/126963618/222939283-4f9f5ec9-e0d7-4cf8-bcb3-ccc9575944f4.png)

[testpoll.zip(https://github.com/mat1jaczyyy/Keyboard-Inspector/files/10890668/test.poll.zip)


https://user-images.githubusercontent.com/126963618/222939409-6c58b2bf-9b42-4e65-afc0-cfc06d8301b4.mp4

**Comment by LoneEvos** [comment]
> And how can I read your mind and your laptop's state? Attach a recording.

my bad i forgot about it

**Comment by mat1jaczyyy** [comment]
sorry i missed the comment reply notification somehow.

your laptop uses PS/2 for the internal keyboard and not usb, you will get really accurate timings on your key presses but you probably can't register multiple keypresses simultaneously without a few ms delay (your keyboard will chord split)

you can test for this by trying to press a lot of keys simultaneously and then look at the delta graph between 0 and 8 ms
